CREATE TABLE Users (
	UserID INT IDENTITY(1, 1),
	FullName NVARCHAR(250) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Password VARCHAR(30) NOT NULL,
	BudgetAmount DECIMAL(18, 2) NULL,

	CONSTRAINT PK_Users PRIMARY KEY (UserID)
)
