CREATE TABLE Cities (
	CityID INT IDENTITY(1, 1),
	Name NVARCHAR(250) NOT NULL,
	IsCapitalCity BIT NOT NULL DEFAULT 0,
	CountryID TINYINT NOT NULL,

	CONSTRAINT PK_Cities PRIMARY KEY (CityID),
	CONSTRAINT FK_Cities_Countries FOREIGN KEY (CountryID) REFERENCES Countries(CountryID)
)