CREATE TABLE Trips (
	TripID INT IDENTITY(1, 1),
	Title NVARCHAR(250) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	Price DECIMAL(18, 2) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	CountryID TINYINT NOT NULL,

	CONSTRAINT PK_Trips PRIMARY KEY (TripID),
	CONSTRAINT FK_Trips_Countries FOREIGN KEY (CountryID)
		REFERENCES Countries(CountryID)
)
