CREATE TABLE Users (
	UserID INT IDENTITY(1, 1),
	FullName NVARCHAR(250) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Password VARCHAR(30) NOT NULL,
	Budget DECIMAL(18, 2) NULL,
	RoleID INT NOT NULL DEFAULT 1, -- "User"

	CONSTRAINT PK_Users PRIMARY KEY (UserID),
	CONSTRAINT UQ_Users_Email UNIQUE (Email),
	CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleID) REFERENCES Roles(RoleID)
)

